# debating if I want to actually do this or not.
name: Scheduled Cloudflare Pages Build

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"